repoURL: "https://github.com/Kong/charts.git"
path: "charts/kong"
targetRevision: "kong-2.41.1"

image:
  repository: kong/kong-gateway
  tag: "3.8.0.0"

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

autoscaling:
  enabled: true
  maxReplicas: 3
  minReplicas: 3

ingressController:
  enabled: false
  installCRDs: false

podDisruptionBudget:
  enabled: true
  minAvailable: 1

resources:
  requests:
    cpu: 4
    memory: "6Gi"
  limits:
    cpu: 4
    memory: "6Gi"

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  nginx_worker_processes: "4"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  OTEL_AGENT_HOST:
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP

proxy:
  type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: alb
    path: "/*"
    annotations:
      # Enable for AWS ALB
      # Documentation on the annotations is under
      # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/backend-protocol: HTTP

      # Healthcheck config
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      # There is no route and service for "/" so Kong returns a 404.
      # If Kong is not running the health check will time out instead.
      # We could use an url where Kong returns 200, but this URL will depend
      # on a backend service. So Kong would be down, when this service is down.
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/success-codes: '404'

      # preserve client ip
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      
